resolver: lts-6.30
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
        sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51

build:
  haddock-hyperlink-source: false

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/d0kt0r0/MusicW.git
    commit: 125a42f6c998aaafe60868d0b804a1776a0598af
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.3.1
- reflex-dom-0.3
- reflex-0.4.0
- ref-tf-0.4
- haskell-src-exts-1.16.0.1
- reflex-dom-contrib-0.4.1
- string-conv-0.1.2
- tuple-0.3.0.2
- OneTuple-0.2.1
